language: java
script: mvn install -Popenshift
notifications:
  email:
      recipients:
        forsrinivasan@gmail.com
        anthonilawrance@gmail.com
        skrishna.joy@gmail.com
deploy:
  provider: openshift
  user: "vzwallet@gmail.com"
  password: "Verizon1!" # can be encrypted
  domain: "vzw"
  app: "onepoint"
  skip_cleanup: true
  #deployment_branch: "vztest"
